version: 0.2

phases:
  install:
    runtime-versions:
      dotnet: 3.1
    commands:
      - cat /etc/os-release
      - yum update -y
  pre_build:
    commands:
      - yum install -y redis
      - redis-server --daemonize yes
  build:
    commands:
      - echo Build started on `date`
      - dotnet test Source/Nautilus.TestSuite.UnitTests
      - dotnet test Source/Nautilus.TestSuite.IntegrationTests
  post_build:
    commands:
      - mkdir nautilus-data
      - mkdir nautilus-exec
      - dotnet publish Source/NautilusData/NautilusData.csproj -c Release -o nautilus-data
      - dotnet publish Source/NautilusExecutor/NautilusExecutor.csproj -c Release -o nautilus-exec
      - echo Build completed on `date`

artifacts:
  files:
    - 'nautilus-data/**/*'
    - 'nautilus-exec/**/*'
  name: nautilus-services-$CODEBUILD_BUILD_NUMBER
  discard-paths: no
