name: build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.301
      - name: Install dependencies
        run: sudo apt-get install redis-server
      - name: Test
        run: |
          dotnet restore
          dotnet test Source/Nautilus.TestSuite.UnitTests
          dotnet test Source/Nautilus.TestSuite.IntegrationTests
      - name: Build
        run: |
          - dotnet publish Source/NautilusData/NautilusData.csproj -c Release -o
          - dotnet publish Source/NautilusExecutor/NautilusExecutor.csproj -c Release -o
          - bash codecov.sh
