name: build-develop

on:
  push:
    branches: [ develop ]

jobs:

  build-test:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup Environment
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.302

      - name: Set Version
        run: |
          echo ::set-env name=VERSION::$(cat Source/version.txt)
          echo ::set-env name=BUILD_NUMBER::$(echo $GITHUB_RUN_NUMBER)

      - name: Set Naming
        run: |
          echo ::set-env name=NAUTILUS_VERSION::$(echo $VERSION.$BUILD_NUMBER-beta)
          echo ::set-env name=NAUTILUS_RELEASE_NAME::$(echo Nautilus-$VERSION.$BUILD_NUMBER-beta)

      - name: Check Naming
        run: |
          echo version: $VERSION
          echo build: $BUILD_NUMBER
          echo tag: $NAUTILUS_VERSION
          echo release: $NAUTILUS_RELEASE_NAME

      - name: Install dependencies
        run: |
          sudo apt-get install redis-server
          git clone --recursive https://github.com/RedisTimeSeries/RedisTimeSeries.git
          cd RedisTimeSeries
          sudo make build
          pwd
          redis-server --daemonize yes
          redis-cli MODULE LOAD /bin/redistimeseries.so
          cd -

      - name: Test
        run: |
          dotnet restore
          dotnet test Source/Nautilus.TestSuite.UnitTests
          dotnet test Source/Nautilus.TestSuite.IntegrationTests
