name: build

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup Environment
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.302
      - name: Install dependencies
        run: |
          sudo apt-get install redis-server
          redis-server --daemonize yes
      - name: Test
        run: |
          dotnet restore
          dotnet test Source/Nautilus.TestSuite.UnitTests
          dotnet test Source/Nautilus.TestSuite.IntegrationTests
          codecov -f "coverage.xml"
      - name: Code Coverage
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./coverage.xml
          fail_ci_if_error: true

      - name: Release
        run: |
          dotnet publish Source/NautilusData/NautilusData.csproj -c Release
          dotnet publish Source/NautilusExecutor/NautilusExecutor.csproj -c Release
